# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(640, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(LoginWindow.sizePolicy().hasHeightForWidth())
        LoginWindow.setSizePolicy(sizePolicy)
        LoginWindow.setStyleSheet("background-color: rgb(6, 38, 111);\n"
"font: 14pt \"DejaVu Serif\";\n"
"color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(LoginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(140, 100, 391, 261))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setStyleSheet("text-align: center;\n"
"font: 16pt \"DejaVu Serif\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setProperty("setAlignment", "")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.line_login = QtWidgets.QLineEdit(self.layoutWidget)
        self.line_login.setStyleSheet("border:none;\n"
"background-color: rgb(70, 113, 213);")
        self.line_login.setMaxLength(20)
        self.line_login.setPlaceholderText("")
        self.line_login.setObjectName("line_login")
        self.verticalLayout_3.addWidget(self.line_login)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.line_password = QtWidgets.QLineEdit(self.layoutWidget)
        self.line_password.setStyleSheet("border: none;\n"
"background-color: rgb(70, 113, 213);")
        self.line_password.setMaxLength(20)
        self.line_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.line_password.setObjectName("line_password")
        self.verticalLayout_3.addWidget(self.line_password)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.register_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.register_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(42, 68, 128);\n"
"    color: white;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(18, 64, 171);\n"
"}")
        self.register_btn.setObjectName("register_btn")
        self.horizontalLayout.addWidget(self.register_btn)
        self.log_in_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.log_in_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(42, 68, 128);\n"
"    color: white;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(18, 64, 171);\n"
"}")
        self.log_in_btn.setObjectName("log_in_btn")
        self.horizontalLayout.addWidget(self.log_in_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalWidget_2.setGeometry(QtCore.QRect(520, 410, 111, 54))
        self.verticalWidget_2.setObjectName("verticalWidget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalWidget_2)
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.credits = QtWidgets.QLabel(self.verticalWidget_2)
        self.credits.setStyleSheet("font: italic 10pt \"Droid Sans Fallback\";")
        self.credits.setObjectName("credits")
        self.verticalLayout_4.addWidget(self.credits)
        self.label_5 = QtWidgets.QLabel(self.verticalWidget_2)
        self.label_5.setStyleSheet("font: italic 10pt \"Droid Sans Fallback\";\n"
"")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        LoginWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "Авторизация"))
        self.label.setText(_translate("LoginWindow", "Авторизация"))
        self.label_2.setText(_translate("LoginWindow", "Логин"))
        self.label_3.setText(_translate("LoginWindow", "Пароль"))
        self.register_btn.setText(_translate("LoginWindow", "Регистрация"))
        self.log_in_btn.setText(_translate("LoginWindow", "Войти"))
        self.credits.setText(_translate("LoginWindow", "v. 0.0.1"))
        self.label_5.setText(_translate("LoginWindow", "made by CXDER"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoginWindow = QtWidgets.QMainWindow()
    ui = Ui_LoginWindow()
    ui.setupUi(LoginWindow)
    LoginWindow.show()
    sys.exit(app.exec_())
