# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Manager.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ManagerWindow(object):
    def setupUi(self, ManagerWindow):
        ManagerWindow.setObjectName("ManagerWindow")
        ManagerWindow.resize(640, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ManagerWindow.sizePolicy().hasHeightForWidth())
        ManagerWindow.setSizePolicy(sizePolicy)
        ManagerWindow.setStyleSheet("background-color: rgb(6, 38, 111);\n"
"font: 14pt \"DejaVu Serif\";\n"
"color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(ManagerWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalWidget_2.setGeometry(QtCore.QRect(520, 410, 111, 54))
        self.verticalWidget_2.setObjectName("verticalWidget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalWidget_2)
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.credits = QtWidgets.QLabel(self.verticalWidget_2)
        self.credits.setStyleSheet("font: italic 10pt \"Droid Sans Fallback\";")
        self.credits.setObjectName("credits")
        self.verticalLayout_4.addWidget(self.credits)
        self.label_5 = QtWidgets.QLabel(self.verticalWidget_2)
        self.label_5.setStyleSheet("font: italic 10pt \"Droid Sans Fallback\";\n"
"")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.logout_btn = QtWidgets.QPushButton(self.centralwidget)
        self.logout_btn.setGeometry(QtCore.QRect(540, 10, 87, 27))
        self.logout_btn.setObjectName("logout_btn")
        self.add_password_btn = QtWidgets.QPushButton(self.centralwidget)
        self.add_password_btn.setGeometry(QtCore.QRect(80, 355, 440, 29))
        self.add_password_btn.setObjectName("add_password_btn")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(80, 70, 441, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setStyleSheet("font-weight: bold;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setStyleSheet("font-weight: bold;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.service_line = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.service_line.sizePolicy().hasHeightForWidth())
        self.service_line.setSizePolicy(sizePolicy)
        self.service_line.setObjectName("service_line")
        self.horizontalLayout.addWidget(self.service_line)
        self.password_line = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.password_line.sizePolicy().hasHeightForWidth())
        self.password_line.setSizePolicy(sizePolicy)
        self.password_line.setObjectName("password_line")
        self.horizontalLayout.addWidget(self.password_line)
        self.verticalLayout.addLayout(self.horizontalLayout)
        ManagerWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(ManagerWindow)
        QtCore.QMetaObject.connectSlotsByName(ManagerWindow)

    def retranslateUi(self, ManagerWindow):
        _translate = QtCore.QCoreApplication.translate
        ManagerWindow.setWindowTitle(_translate("ManagerWindow", "Менеджер"))
        self.credits.setText(_translate("ManagerWindow", "v. 0.0.1"))
        self.label_5.setText(_translate("ManagerWindow", "made by CXDER"))
        self.logout_btn.setText(_translate("ManagerWindow", "Выйти"))
        self.add_password_btn.setText(_translate("ManagerWindow", "Добавить пароль"))
        self.label.setText(_translate("ManagerWindow", "Сервис"))
        self.label_2.setText(_translate("ManagerWindow", "Пароль"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ManagerWindow = QtWidgets.QMainWindow()
    ui = Ui_ManagerWindow()
    ui.setupUi(ManagerWindow)
    ManagerWindow.show()
    sys.exit(app.exec_())
