# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/Manager.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ManagerWindow(object):
    def setupUi(self, ManagerWindow):
        ManagerWindow.setObjectName("ManagerWindow")
        ManagerWindow.resize(640, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ManagerWindow.sizePolicy().hasHeightForWidth())
        ManagerWindow.setSizePolicy(sizePolicy)
        ManagerWindow.setStyleSheet("background-color: rgb(6, 38, 111);\n"
"font: 14pt \"DejaVu Serif\";\n"
"color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(ManagerWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalWidget_2.setGeometry(QtCore.QRect(520, 410, 111, 54))
        self.verticalWidget_2.setObjectName("verticalWidget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalWidget_2)
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.credits = QtWidgets.QLabel(self.verticalWidget_2)
        self.credits.setStyleSheet("font: italic 10pt \"Droid Sans Fallback\";")
        self.credits.setObjectName("credits")
        self.verticalLayout_4.addWidget(self.credits)
        self.label_5 = QtWidgets.QLabel(self.verticalWidget_2)
        self.label_5.setStyleSheet("font: italic 10pt \"Droid Sans Fallback\";\n"
"")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(220, 170, 198, 80))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 1, 1, 1, 1)
        self.logout_btn = QtWidgets.QPushButton(self.centralwidget)
        self.logout_btn.setGeometry(QtCore.QRect(540, 10, 87, 27))
        self.logout_btn.setObjectName("logout_btn")
        ManagerWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(ManagerWindow)
        QtCore.QMetaObject.connectSlotsByName(ManagerWindow)

    def retranslateUi(self, ManagerWindow):
        _translate = QtCore.QCoreApplication.translate
        ManagerWindow.setWindowTitle(_translate("ManagerWindow", "Менеджер"))
        self.credits.setText(_translate("ManagerWindow", "v. 0.0.1"))
        self.label_5.setText(_translate("ManagerWindow", "made by CXDER"))
        self.label.setText(_translate("ManagerWindow", "TextLabel"))
        self.label_2.setText(_translate("ManagerWindow", "TextLabel"))
        self.label_3.setText(_translate("ManagerWindow", "TextLabel"))
        self.logout_btn.setText(_translate("ManagerWindow", "Выйти"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ManagerWindow = QtWidgets.QMainWindow()
    ui = Ui_ManagerWindow()
    ui.setupUi(ManagerWindow)
    ManagerWindow.show()
    sys.exit(app.exec_())
